/* EUCLIDIAN — navegación de la bandeja del cliente. El cliente consulta únicamente información ya verificada/publicada. */
let CLAVE=sessionStorage.getItem('euclidian_clave')||'';
const F={prioridad:'',naturaleza:'',tema:'',orden:'recientes',pagina:1};
function entrar(e){e.preventDefault();CLAVE=document.getElementById('clave').value;sessionStorage.setItem('euclidian_clave',CLAVE);cargar()}
async function cargar(){const lista=document.getElementById('lista'),btn=document.getElementById('btnRecargar');if(btn)btn.disabled=true;lista.innerHTML='<div class="aviso"><b>Cargando información</b><span>Consultando la información verificada…</span></div>';document.getElementById('paginas').innerHTML='';try{const q=new URLSearchParams({estado:'aprobados',orden:F.orden,pagina:F.pagina});if(F.tema)q.set('tema',F.tema);if(F.prioridad)q.set('prioridad',F.prioridad);if(F.naturaleza)q.set('naturaleza',F.naturaleza);const r=await fetch('/api/documentos?'+q,{headers:{'x-clave':CLAVE}});if(r.status===401){sessionStorage.removeItem('euclidian_clave');document.getElementById('puerta').hidden=false;document.getElementById('mal').textContent='No se pudo validar el acceso.';lista.innerHTML='';return}const data=await r.json();if(!r.ok)throw new Error(data.detalle||data.error);document.getElementById('puerta').hidden=true;document.getElementById('mal').textContent='';document.getElementById('cab').hidden=false;document.getElementById('controles').hidden=false;document.getElementById('barra').hidden=false;pintar('gPrioridad',data.prioridad||{});pintar('gNaturaleza',data.naturaleza||{});marcarActivos();poblarTemas(data.temas||[]);const s=document.getElementById('sello');if(s&&data.actualizado){const f=new Date(data.actualizado);s.textContent='Actualizado el '+f.toLocaleDateString('es-CO',{day:'numeric',month:'long'})+', '+f.toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit'})}if(!data.documentos.length){lista.innerHTML='<div class="aviso"><b>No hay resultados con estos filtros.</b><span>Prueba con otro criterio de búsqueda.</span></div>';return}lista.innerHTML=data.documentos.map(ficha).join('');paginacion(data);window.scrollTo({top:0,behavior:'smooth'})}catch(e){lista.innerHTML='<div class="error"><b>No se pudo cargar la información.</b><span>Inténtalo de nuevo en unos momentos.</span></div>'}finally{if(btn)btn.disabled=false}}
function pintar(grupo,conteos){document.querySelectorAll('#'+grupo+' button').forEach(b=>{const m=b.querySelector('b');if(m)m.textContent=conteos[b.dataset.v]===undefined?'':conteos[b.dataset.v]})}
function poblarTemas(temas){const sel=document.getElementById('selTema'),actual=sel.value,orden=[...temas].sort((a,b)=>nombreTema(a).localeCompare(nombreTema(b),'es'));sel.innerHTML='<option value="">Todos los temas</option>'+orden.map(t=>`<option value="${t}">${nombreTema(t)}</option>`).join('');sel.value=actual}
function paginacion(data){const cont=document.getElementById('paginas'),{pagina,paginas,total,porPagina}=data;if(!total){cont.innerHTML='';return}const primero=(pagina-1)*porPagina+1,ultimo=Math.min(pagina*porPagina,total);let html=`<div class="rango">${primero}–${ultimo} de ${total}</div>`;if(paginas>1){html+=`<button onclick="irA(${pagina-1})" ${pagina<=1?'disabled':''}>‹</button>`;const nums=new Set([1,paginas,pagina,pagina-1,pagina+1]);const orden=[...nums].filter(n=>n>=1&&n<=paginas).sort((a,b)=>a-b);let previo=0;orden.forEach(n=>{if(n-previo>1)html+='<span aria-hidden="true">…</span>';html+=`<button onclick="irA(${n})" aria-current="${n===pagina}">${n}</button>`;previo=n});html+=`<button onclick="irA(${pagina+1})" ${pagina>=paginas?'disabled':''}>›</button>`}cont.innerHTML=html}
function irA(n){if(n<1)return;F.pagina=n;cargar()}
function marcarActivos(){const n=[F.prioridad,F.naturaleza,F.tema,F.orden!=='recientes'?F.orden:''].filter(Boolean).length;const marca=document.getElementById('activos');if(marca)marca.textContent=n?' · '+n+' filtro'+(n===1?'':'s'):'';const btn=document.getElementById('btnLimpiar');if(btn)btn.hidden=n===0}
function limpiar(){F.prioridad='';F.naturaleza='';F.tema='';F.orden='recientes';F.pagina=1;document.getElementById('selTema').value='';document.getElementById('selOrden').value='recientes';document.querySelectorAll('#gPrioridad button,#gNaturaleza button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===0)));cargar()}
function grupoClic(grupo,campo){document.getElementById(grupo).addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;F[campo]=b.dataset.v;F.pagina=1;document.querySelectorAll('#'+grupo+' button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));cargar()})}
grupoClic('gPrioridad','prioridad');grupoClic('gNaturaleza','naturaleza');document.getElementById('selTema').addEventListener('change',e=>{F.tema=e.target.value;F.pagina=1;cargar()});document.getElementById('selOrden').addEventListener('change',e=>{F.orden=e.target.value;F.pagina=1;cargar()});if(CLAVE)cargar();else document.getElementById('puerta').hidden=false;
