/* EUCLIDIAN — bloques y armado de la ficha. La ficha separa diagnóstico fiscal, contenido jurídico, identificación, vigencia, relaciones y trazabilidad. El fiscal revisa; la ficha informa. */
(function(){if(!document.querySelector('link[data-euclidian-detalle]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/detalle.css';l.dataset.euclidianDetalle='1';document.head.appendChild(l)}})();
function textoMotivo(m){const s=String(m||'').trim();if(!s)return '';return s.replace(/^CRITICAL:\s*/i,'').replace(/Controles técnicos superados; falta revisión humana del contenido y su aplicación\.?/i,'La fuente primaria permite confirmar el contenido y su aplicación al caso concreto.').replace(/No se pudo leer la fuente oficial:\s*404 Client Error: Not Found for url:\s*\S+/i,'La fuente individual registrada no está accesible actualmente. La ficha conserva la información corroborada en el índice oficial DIAN.').replace(/No se pudo leer la fuente oficial:\s*\S+/i,'La fuente individual registrada no está accesible actualmente. La ficha conserva la información corroborada en el índice oficial DIAN.').replace(/\s+/g,' ');}
function bloqueDiagnostico(d){const resultado=String(d.evaluacion_resultado||'').toUpperCase();const fuente=String(d.estado_fuente_verificacion||'').toLowerCase();const fuenteContrastada=fuente==='verificado_oficial';const fuenteDisponible=!!d.enlace_oficial;const fallidas=Array.isArray(d.evaluacion_reglas_fallidas)?d.evaluacion_reglas_fallidas:[];const motivos=(Array.isArray(d.evaluacion_motivos)?d.evaluacion_motivos:[]).map(textoMotivo).filter(Boolean);const vigencia=d.estado_vigencia&&d.estado_vigencia!=='desconocido';const alcance=!!(d.clasificacion_obligatoriedad||d.materia||(d.temas||[]).length);const completa=resultado==='APPROVE'&&fuenteContrastada;let estado,clase,detalle;if(completa){estado='Ficha contrastada con la fuente DIAN';clase='diagnostico-ok';detalle='Incluye identificación, alcance, vigencia y fuente primaria para sustentar la consulta.';}else if(fuenteDisponible){estado='Ficha con fuente primaria disponible';clase='diagnostico-revision';detalle='Usa el enlace oficial para confirmar excepciones, fechas y aplicación al caso concreto.';}else{estado='Registro localizado en el índice DIAN';clase='diagnostico-pendiente';detalle='La ficha organiza los datos disponibles. Antes de aplicarla, verifica el documento individual en la DIAN.';}const criterios=[['Fuente primaria',fuenteDisponible],['Fuente contrastada',fuenteContrastada],['Vigencia identificada',vigencia],['Alcance identificado',alcance]].map(([nombre,ok])=>`<span>${ok?'✓':'•'} ${esc(nombre)}</span>`).join('');const reglas=fallidas.length?`<div class="diagnostico-reglas"><span>Puntos para validar en la fuente</span><div>${fallidas.map(x=>`<span>${esc(String(x).replace(/^FUENTE_OFICIAL$/,'Evidencia de fuente'))}</span>`).join('')}</div></div>`:'';const notas=motivos.length?`<ul class="diagnostico-motivos">${motivos.slice(0,4).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';const fecha=d.fuente_verificada_en?`<div class="diagnostico-meta">Fuente consultada: ${fechaCorta(d.fuente_verificada_en)}</div>`:'';return `<div class="diagnostico ${clase}"><div class="diagnostico-cab"><strong>Dictamen de la ficha</strong><span>${estado}</span></div>${fecha}<p>${detalle}</p><div class="diagnostico-reglas"><span>Elementos revisados</span><div>${criterios}</div></div>${reglas}${notas}</div>`;}
function enlaceDianSeguro(url){try{const u=new URL(String(url||''));return u.protocol==='https:'&&u.hostname.endsWith('.dian.gov.co')?u.href:'';}catch(_){return '';}}
function bloqueAplicacion(d){const zonas=(d.zonas_afectadas||[]).filter(Boolean);const plazo=(d.plazos_mencionados||[]).find(Boolean);const tema=(d.temas||[]).filter(t=>!String(t).startsWith('dian:')&&t!=='boletin_mensual').map(nombreTema).slice(0,3);const alcance=d.clasificacion_obligatoriedad==='obligatorio_dian_y_contribuyentes'?'Norma de aplicación general':d.clasificacion_obligatoriedad==='obligatorio_dian_solo'?'Criterio doctrinal de la DIAN':tema.length?`Tema: ${tema.join(' · ')}`:'Criterio informativo de la DIAN';const destinatario=zonas.length?zonas.slice(0,4).join(', '):tema.length?tema.join(' · '):'Determinar según el caso consultado';let siguiente='Contrasta el criterio con los hechos, el periodo y la obligación del caso consultado.';if(plazo)siguiente='Registra el plazo y confirma a qué obligación, periodo y contribuyente aplica.';else if(d.estado_vigencia&&d.estado_vigencia!=='vigente')siguiente='Verifica el estado de vigencia antes de usarla en una declaración o concepto.';else if(zonas.length)siguiente='Confirma el domicilio, la seccional o la zona del contribuyente.';const fuente=enlaceDianSeguro(d.enlace_oficial);const accionFuente=fuente?`<a class="abrir-fuente" href="${esc(fuente)}" target="_blank" rel="noopener noreferrer">Abrir fuente DIAN</a>`:'<span class="fuente-pendiente">Consulta el índice oficial DIAN</span>';return `<section class="guia-uso" aria-label="Guía práctica"><div class="guia-rotulo">Guía para tu trabajo</div><div class="guia-pasos"><div><span>Qué cambia</span><strong>${esc(alcance)}</strong></div><div><span>A quién afecta</span><strong>${esc(destinatario)}</strong></div><div><span>Qué revisar</span><strong>${esc(siguiente)}</strong></div></div><div class="guia-accion">${accionFuente}</div></section>`;}
function bloqueRespuesta(d){if(!d.problema_juridico&&!d.tesis_juridica)return '';const pregunta=d.problema_juridico?`<div class="consulta"><span class="consulta-rotulo">Lo que le preguntaron a la DIAN</span><p>${esc(d.problema_juridico)}</p></div>`:'';if(!d.tesis_juridica)return `<div class="respuesta solo-pregunta">${pregunta}</div>`;const r=d.tesis_respuesta||'';const marca=r==='si'?'Sí':r==='no'?'No':r==='matizada'?'Depende':'—';return `<div class="respuesta">${pregunta}<div class="resp-cab"><span class="resp-marca">${marca}</span> Lo que respondió</div><p>${esc(d.tesis_juridica)}</p></div>`;}
function bloqueContenido(d){const humano=String(d.resumen_humano||'').trim();const borrador=String(d.resumen_borrador||'').trim();const texto=d.descripcion_limpia||d.contenido||'';const partes=[];if(humano)partes.push(`<div class="resumen-ficha"><span class="resumen-rotulo">En una mirada</span><p>${esc(humano)}</p></div>`);else if(borrador){partes.push(`<div class="borrador"><div class="borrador-cab"><span>Síntesis de la ficha</span></div><p>${esc(borrador)}</p><div class="ojo">Consulta el enlace oficial antes de aplicarla a un caso concreto.</div></div>`)}else if(texto)partes.push(`<div class="sin-ficha"><span class="sin-ficha-rotulo">Descripción del índice DIAN</span><p>${esc(texto)}</p></div>`);return partes.join('');}
function bloqueTextoFuente(d){const texto=String(d.texto_completo||'').trim();if(!texto)return '';return `<details class="detalle-seccion texto-fuente"><summary>Texto oficial disponible</summary><p class="cobertura-nota">Consulta el enlace de la DIAN si necesitas revisar formato, anexos o el texto completo en su publicación original.</p><pre>${esc(texto)}</pre></details>`;}
function dato(label,value,clase=''){if(value===null||value===undefined||String(value).trim()==='')return '';return `<div class="ficha-dato ${clase}"><span>${esc(label)}</span><strong>${esc(String(value))}</strong></div>`;}
function listaDato(label,arr,max=8){const a=Array.isArray(arr)?arr.filter(Boolean).slice(0,max):[];if(!a.length)return '';return `<div class="ficha-dato ficha-lista"><span>${esc(label)}</span><strong>${a.map(esc).join(' · ')}</strong></div>`;}
function bloqueIdentificacion(d){const fecha=fechaDocumentoConfiable(d)?dato('Fecha del documento',fechaCorta(d.fecha_publicacion),'principal'):'';const filas=[dato('Tipo de documento',d.tipo_documento),dato('Número',d.numero_resolucion),d.numero_interno?dato('Radicado DIAN',d.numero_interno):'',dato('Entidad emisora',d.entidad_emisora),dato('Diario Oficial',d.diario_oficial),fecha,d.fecha_publicacion_web?dato('Publicada en la web DIAN',fechaCorta(d.fecha_publicacion_web)):''].filter(Boolean).join('');return filas?`<details class="detalle-seccion ficha-identificacion"><summary>Datos del documento</summary><div class="ficha-datos">${filas}</div></details>`:'';}
function bloqueVigencia(d){const retro=d.tiene_efectos_retroactivos===true?'Sí':d.tiene_efectos_retroactivos===false?'No':'No determinado';const filas=[dato('Estado',d.estado_vigencia||'No determinado'),d.fecha_entrada_vigencia?dato('Rige desde',fechaCorta(d.fecha_entrada_vigencia)):'',dato('Motivo del estado',d.motivo_cambio_estado),dato('Anotaciones de vigencia',d.anotaciones_vigencia),dato('Efectos retroactivos',retro),listaDato('Años afectados',d.anos_afectados,10),listaDato('Zonas afectadas',d.zonas_afectadas,8),listaDato('Plazos mencionados',d.plazos_mencionados,6)].filter(Boolean).join('');return `<details class="detalle-seccion ficha-vigencia"><summary>Vigencia y efectos</summary><div class="ficha-datos">${filas||'<p class="detalle-vacio">No hay datos adicionales de vigencia registrados.</p>'}</div></details>`;}
function bloqueFuentes(d){const individual=d.enlace_oficial;const indice=d.fuente_raiz||((d.temas||[]).includes('boletin_mensual')?'https://normograma.dian.gov.co/dian/compilacion/novedades_boletines.html':'https://normograma.dian.gov.co/dian/compilacion/tributario.html');const nombreIndice=indice.includes('novedades_boletines')?'Novedades y boletines DIAN':'Normograma tributario DIAN';return `<details class="detalle-seccion fuentes"><summary>Fuentes oficiales</summary>${individual?`<div class="fuente-item"><span class="fuente-estado">Documento DIAN</span><a href="${esc(individual)}" target="_blank" rel="noopener">Abrir documento oficial</a></div>`:''}<div class="fuente-item"><span class="fuente-estado">Índice de procedencia</span><a href="${esc(indice)}" target="_blank" rel="noopener">${esc(nombreIndice)}</a></div>${!individual?'<p class="fuente-nota">La referencia disponible corresponde a la publicación oficial de la DIAN.</p>':''}</details>`;}
function bloqueFuentesFormales(d){const partes=[];if((d.fuentes_formales||[]).length)partes.push(listaDato('Fuentes formales',d.fuentes_formales,10));if((d.doctrina_citada||[]).length)partes.push(listaDato('Doctrina citada',d.doctrina_citada,8));if((d.jurisprudencia_citada||[]).length)partes.push(listaDato('Jurisprudencia citada',d.jurisprudencia_citada,8));if((d.descriptores||[]).length)partes.push(listaDato('Descriptores',d.descriptores,10));return partes.length?`<details class="detalle-seccion"><summary>Fuentes jurídicas y descriptores</summary><div class="ficha-datos">${partes.join('')}</div></details>`:'';}
function bloqueRelaciones(d){
  const despues=Array.isArray(d.modificado_por)?d.modificado_por:[];
  const antes=Array.isArray(d.modifica_a)?d.modifica_a:[];
  if(!despues.length&&!antes.length)return '';
  const nodo=(r,tipo)=>{
    const numero=String(r.numero||r.titulo||'Documento relacionado');
    const url=enlaceDianSeguro(r.enlace);
    const fecha=r.fecha?fechaCorta(r.fecha):'';
    const accion=String(r.accion||(tipo==='despues'?'Norma posterior':'Norma relacionada'));
    const titulo=url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(numero)} <span aria-hidden="true">↗</span></a>`:`<strong>${esc(numero)}</strong>`;
    return `<li class="timeline-nodo ${tipo}"><span class="timeline-punto" aria-hidden="true"></span><div><small>${esc(accion)}</small>${titulo}${fecha?`<time>${esc(fecha)}</time>`:''}</div></li>`;
  };
  const prev=antes.slice(0,5).map(r=>nodo(r,'antes')).join('');
  const post=despues.slice(0,5).map(r=>nodo(r,'despues')).join('');
  const extra=Math.max(0,antes.length-5)+Math.max(0,despues.length-5);
  return `<section class="relaciones-vivas" aria-label="Historia y relaciones del documento"><div class="relaciones-cab"><span class="relaciones-glifo" aria-hidden="true">⌁</span><div><small>HISTORIA NORMATIVA</small><strong>Cómo se conecta este documento</strong></div></div><ol class="timeline-relaciones">${prev}<li class="timeline-nodo actual"><span class="timeline-punto" aria-hidden="true"></span><div><small>Este documento</small><strong>${esc(d.numero_resolucion||tituloFicha(d))}</strong>${fechaDocumentoConfiable(d)?`<time>${esc(fechaCorta(d.fecha_publicacion))}</time>`:''}</div></li>${post}</ol>${extra?`<p class="timeline-mas">+${extra} relaciones adicionales disponibles en los detalles.</p>`:''}</section>`;
}
function bloquePlazo(d){const p=(d.plazos_mencionados||[])[0];if(!p)return '';const f=fechaDePlazo(p);if(f&&diasHasta(f)<0)return '';let marca='';if(f){const n=diasHasta(f);marca=`<span class="restan ${n>30?'lejos':''}">${n===0?'hoy':n===1?'mañana':'faltan '+n+' días'}</span>`;}return `<div class="plazo"><div class="plazo-cab"><span>Plazo</span>${marca}</div><p>${esc(p)}</p></div>`;}
function bloqueClasificacion(d){const temas=(d.temas||[]).filter(t=>!t.startsWith('dian:')&&t!=='boletin_mensual');const vigenciaIndeterminada=!d.estado_vigencia||d.estado_vigencia==='desconocido';const fuerza=[`<span class="${vigenciaIndeterminada?'orienta':d.estado_vigencia!=='vigente'?'alerta':d.clasificacion_obligatoriedad==='obligatorio_dian_y_contribuyentes'?'obliga':'orienta'}">${leyenda(d)}</span>`,d.tiene_efectos_retroactivos===true?'<span class="alerta">puede afectar años anteriores</span>':''].filter(Boolean).join('');const materias=[d.materia?`<span class="materia">${esc(d.materia)}</span>`:'',...temas.slice(0,8).map(t=>`<span>${nombreTema(t)}</span>`)].filter(Boolean).join('');return `<div class="clasificacion"><div class="grupo-marcas"><span class="clas-rotulo">Cómo usarla</span><div class="marcas">${fuerza||'<span>Consulta la fuente oficial</span>'}</div></div><div class="grupo-marcas"><span class="clas-rotulo">Tema</span><div class="marcas">${materias||'<span>Consulta la fuente oficial</span>'}</div></div></div>`;}
function tituloFicha(d){return String(d.titulo||d.numero_resolucion||'Documento DIAN').replace(/\s+(?:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)\s+\d{1,2}\s*$/i,'').trim();}
function bloqueEstadoClave(d){
  const estado=String(d.estado_vigencia||'desconocido').toLowerCase();
  const vigente=estado==='vigente';
  const desconocido=!estado||estado==='desconocido';
  const vigenciaClase=vigente?'ok':desconocido?'pendiente':'alerta';
  const vigenciaTexto=vigente?'Vigente':desconocido?'Vigencia por confirmar':String(d.estado_vigencia||'No vigente');
  const fuente=String(d.estado_fuente_verificacion||'').toLowerCase();
  const fuenteVerificada=fuente==='verificado_oficial';
  const fuenteDisponible=!!enlaceDianSeguro(d.enlace_oficial);
  const fuenteClase=fuenteVerificada?'ok':fuenteDisponible?'orienta':'pendiente';
  const fuenteTexto=fuenteVerificada?'Fuente oficial contrastada':fuenteDisponible?'Fuente DIAN disponible':'Referencia en índice DIAN';
  const relaciones=((d.modificado_por||[]).length+(d.modifica_a||[]).length);
  const relacionTexto=relaciones?relaciones+' relación'+(relaciones===1?'':'es')+' normativa'+(relaciones===1?'':'s'):'Sin relaciones registradas';
  return `<div class="estado-clave" aria-label="Estado esencial del documento">
    <div class="estado-clave-item ${vigenciaClase}"><span class="estado-figura" aria-hidden="true">${vigente?'○':desconocido?'◇':'×'}</span><div><small>Vigencia</small><strong>${esc(vigenciaTexto)}</strong></div></div>
    <div class="estado-clave-item ${fuenteClase}"><span class="estado-figura" aria-hidden="true">${fuenteVerificada?'●':fuenteDisponible?'◐':'○'}</span><div><small>Evidencia</small><strong>${esc(fuenteTexto)}</strong></div></div>
    <div class="estado-clave-item neutro"><span class="estado-figura" aria-hidden="true">${relaciones?'⌁':'·'}</span><div><small>Contexto</small><strong>${esc(relacionTexto)}</strong></div></div>
  </div>`;
}

function bloqueAccionesLectura(d){
  const fuente=enlaceDianSeguro(d.enlace_oficial);
  const referencia=[d.numero_resolucion,tituloFicha(d),fechaDocumentoConfiable(d)?fechaLarga(d.fecha_publicacion):''].filter(Boolean).join(' · ');
  return `<div class="ficha-acciones-lectura" aria-label="Acciones del documento">${fuente?`<a class="accion-documento primaria" href="${esc(fuente)}" target="_blank" rel="noopener noreferrer"><span>Fuente DIAN</span><b aria-hidden="true">↗</b></a>`:''}<button type="button" class="accion-documento secundaria" data-copy-ref="${esc(referencia)}"><span>Copiar referencia</span><b aria-hidden="true">⧉</b></button></div>`;
}
function ficha(d){const s=señal(d);const marcaNueva=d.es_nuevo?'<span class="nuevo">Publicación reciente</span>':'';const lateral=[bloquePlazo(d),bloqueRelaciones(d)].filter(Boolean).join('');const descriptores=(d.descriptores||[]).length?`<ul>${d.descriptores.slice(0,10).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';const fuente=enlaceDianSeguro(d.enlace_oficial);const codigo=fuente?`<a class="codigo codigo-enlace" href="${esc(fuente)}" target="_blank" rel="noopener noreferrer" aria-label="Abrir ${esc(d.numero_resolucion)} en la DIAN">${esc(d.numero_resolucion)} <span aria-hidden="true">↗</span></a>`:`<span class="codigo codigo-texto">${esc(d.numero_resolucion)}</span>`;return `<article data-id="${d.id}" class="t-${s.tono}${d.resumen_humano?' escrito':''}${d.es_nuevo?' nuevo-doc':''}"><div class="cintas">${marcaNueva}<span class="cinta">${s.rotulo}</span></div><div class="fila-id">${glifo(d)}${codigo}${d.numero_interno?`<span class="interno">Radicado ${esc(d.numero_interno)}</span>`:''}${fechaPrincipal(d)}</div><h2>${esc(tituloFicha(d))}</h2>${bloqueEstadoClave(d)}${bloqueAccionesLectura(d)}<div class="cuerpo"><div class="principal">${bloqueContenido(d)}${bloqueAplicacion(d)}${bloqueRespuesta(d)}${bloqueVigencia(d)}${bloqueClasificacion(d)}${bloqueFuentes(d)}${bloqueFuentesFormales(d)}${bloqueIdentificacion(d)}${d.descripcion_limpia||d.contenido?`<details class="oficial"><summary><span class="abrir">Descripción del índice DIAN</span></summary><p>${esc(d.descripcion_limpia||d.contenido)}</p>${descriptores}</details>`:''}</div>${lateral?`<aside class="lateral">${lateral}</aside>`:''}</div></article>`;}

// Keep the source document distinct from the short description in the index.
const fichaBaseEUCLIDIAN = ficha;
ficha = function(d){
  const html=fichaBaseEUCLIDIAN(d).replace('Ver texto de la DIAN','Descripción del índice DIAN');
  return html.replace('</article>',`${bloqueTextoFuente(d)}${window.euclidianPuedeRevisar?bloqueAcciones(d):''}</article>`);
};

function bloqueAcciones(d){
  const id=String(d.id??'');
  if(!id)return '';
  const attr=esc(id);
  const texto=esc(d.resumen_humano||d.resumen_borrador||'');
  return `<section class="revision-editor" aria-label="Revisión humana"><label for="r-${attr}">Síntesis clara para el usuario</label><textarea id="r-${attr}" maxlength="4000" rows="5" oninput="contar(this.id.slice(2))">${texto}</textarea><div class="revision-ayuda">Separa esta síntesis del texto literal de la DIAN. La revisión humana puede corregirla antes de publicarla.</div><button type="button" data-review-save="${attr}">Guardar síntesis</button><div class="revision-acciones"><button type="button" data-review-decision="aprobar" data-review-id="${attr}">Aprobar y publicar ficha</button><button type="button" class="secundario" data-review-decision="descartar" data-review-id="${attr}">Descartar ficha</button></div></section>`;
}
if(!window.__euclidianReviewActions){window.__euclidianReviewActions=true;document.addEventListener('click',e=>{const save=e.target.closest('[data-review-save]');if(save){guardarResumen(save.dataset.reviewSave);return;}const decision=e.target.closest('[data-review-decision]');if(decision)decidir(decision.dataset.reviewId,decision.dataset.reviewDecision);});}

if(!window.__euclidianCopyReference){window.__euclidianCopyReference=true;document.addEventListener('click',async e=>{const b=e.target.closest('[data-copy-ref]');if(!b)return;const texto=b.dataset.copyRef||'';if(!texto)return;const anterior=b.querySelector('span')?.textContent||'Copiar referencia';try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(texto);}else{const t=document.createElement('textarea');t.value=texto;t.setAttribute('readonly','');t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();}const s=b.querySelector('span');if(s)s.textContent='Referencia copiada';b.classList.add('copiado');setTimeout(()=>{if(s)s.textContent=anterior;b.classList.remove('copiado');},1800);}catch(_){const s=b.querySelector('span');if(s)s.textContent='No se pudo copiar';setTimeout(()=>{if(s)s.textContent=anterior;},1800);}});}
