/* EUCLIDIAN — bloques y armado de la ficha. La ficha separa diagnóstico fiscal, contenido jurídico, identificación, vigencia, relaciones y trazabilidad. El fiscal revisa; la ficha informa. */
(function(){if(!document.querySelector('link[data-euclidian-detalle]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/detalle.css';l.dataset.euclidianDetalle='1';document.head.appendChild(l)}})();
function textoMotivo(m){const s=String(m||'').trim();if(!s)return '';return s.replace(/^CRITICAL:\s*/i,'').replace(/No se pudo leer la fuente oficial:\s*404 Client Error: Not Found for url:\s*\S+/i,'La fuente individual registrada no está accesible actualmente. La ficha conserva la información corroborada en el índice oficial DIAN.').replace(/No se pudo leer la fuente oficial:\s*\S+/i,'La fuente individual registrada no está accesible actualmente. La ficha conserva la información corroborada en el índice oficial DIAN.').replace(/\s+/g,' ');}
function bloqueDiagnostico(d){const persona=!!d.revisado_por_humano;const resultado=String(d.evaluacion_resultado||'').toUpperCase();const autoOk=resultado==='APPROVE';const fallidas=Array.isArray(d.evaluacion_reglas_fallidas)?d.evaluacion_reglas_fallidas:[];const motivos=(Array.isArray(d.evaluacion_motivos)?d.evaluacion_motivos:[]).map(textoMotivo).filter(Boolean);let estado,clase;if(persona){estado=d.publicado_cliente?'Revisada por persona':'Revisada por persona · no publicada';clase=d.publicado_cliente?'diagnostico-ok':'diagnostico-revision';}else if(autoOk){estado='Controles automáticos superados · falta revisión humana';clase='diagnostico-pendiente';}else if(d.control_automatico_en){estado='Control automático · requiere atención';clase='diagnostico-revision';}else{estado='Pendiente de control automático';clase='diagnostico-pendiente';}const reglas=fallidas.length?`<div class="diagnostico-reglas"><span>Aspectos que requieren atención</span><div>${fallidas.map(x=>`<span>${esc(String(x).replace(/^FUENTE_OFICIAL$/,'Evidencia de fuente'))}</span>`).join('')}</div></div>`:'';const detalle=motivos.length?`<ul class="diagnostico-motivos">${motivos.slice(0,5).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:autoOk&&!persona?'<p>Los controles técnicos pasaron. Esto no confirma por sí solo la interpretación jurídica, las excepciones ni la aplicación a un contribuyente.</p>':'<p>La persona revisora no dejó observaciones adicionales.</p>';const fecha=persona&&d.revisado_fiscal_en?`<div class="diagnostico-meta">Revisión humana: ${fechaCorta(d.revisado_fiscal_en)}</div>`:d.control_automatico_en?`<div class="diagnostico-meta">Control automático: ${fechaCorta(d.control_automatico_en)}</div>`:'';return `<div class="diagnostico ${clase}"><div class="diagnostico-cab"><strong>Estado de revisión</strong><span>${estado}</span></div>${fecha}${reglas}${detalle}</div>`;}
function bloqueCobertura(d){const checks=[['Identificación',!!(d.tipo_documento&&d.numero_resolucion&&d.fecha_publicacion)],['Resumen y criterio',!!(d.resumen_humano||d.resumen_borrador||d.descripcion_limpia||d.contenido)],['Pregunta y respuesta',!!(d.problema_juridico||d.tesis_juridica)],['Vigencia',!!(d.estado_vigencia||d.fecha_entrada_vigencia||d.anotaciones_vigencia)],['Clasificación',!!(d.materia||((d.temas||[]).length)||d.clasificacion_obligatoriedad)],['Fuentes jurídicas',!!(((d.fuentes_formales||[]).length)||((d.doctrina_citada||[]).length)||((d.jurisprudencia_citada||[]).length))],['Fuente primaria',!!d.enlace_oficial]];const completas=checks.filter(x=>x[1]).length;const lista=checks.map(x=>`<li class="cobertura-${x[1]?'ok':'faltante'}"><span>${x[1]?'✓':'—'}</span>${esc(x[0])}</li>`).join('');return `<details class="detalle-seccion cobertura"><summary>Cobertura de la ficha · ${completas}/${checks.length} bloques con información</summary><ul class="cobertura-lista">${lista}</ul><p class="cobertura-nota">Esta cobertura describe la información registrada en EUCLIDIAN; no sustituye la revisión fiscal ni afirma contenido que no esté disponible en la fuente.</p></details>`;}
function bloqueRespuesta(d){if(!d.problema_juridico&&!d.tesis_juridica)return '';const pregunta=d.problema_juridico?`<div class="consulta"><span class="consulta-rotulo">Lo que le preguntaron a la DIAN</span><p>${esc(d.problema_juridico)}</p></div>`:'';if(!d.tesis_juridica)return `<div class="respuesta solo-pregunta">${pregunta}</div>`;const r=d.tesis_respuesta||'';const marca=r==='si'?'Sí':r==='no'?'No':r==='matizada'?'Depende':'—';return `<div class="respuesta">${pregunta}<div class="resp-cab"><span class="resp-marca">${marca}</span> Lo que respondió</div><p>${esc(d.tesis_juridica)}</p></div>`;}
function bloqueContenido(d){const humano=String(d.resumen_humano||'').trim();const borrador=String(d.resumen_borrador||'').trim();const texto=d.descripcion_limpia||d.contenido||'';const partes=[];if(humano)partes.push(`<div class="resumen-ficha"><span class="resumen-rotulo">${d.revisado_por_humano?'Síntesis revisada por persona':'Síntesis humana · pendiente de aprobación'}</span><p>${esc(humano)}</p>${!d.revisado_por_humano?'<div class="ojo">La autoría humana no equivale a aprobación para publicar.</div>':''}</div>`);else if(borrador){const avisos=(d.borrador_advertencias||[]).length?`<div class="ojo">Pendiente: ${(d.borrador_advertencias||[]).map(esc).join(' · ')}</div>`:'<div class="ojo">Borrador automático; confirma cada afirmación en la fuente antes de usarlo.</div>';partes.push(`<div class="borrador"><div class="borrador-cab"><span>Borrador de síntesis · no revisado</span></div><p>${esc(borrador)}</p>${avisos}</div>`)}else if(texto)partes.push(`<div class="sin-ficha"><span class="sin-ficha-rotulo">Descripción del índice DIAN · no es el texto íntegro</span><p>${esc(texto)}</p></div>`);return partes.join('');}
function bloqueTextoFuente(d){const texto=String(d.texto_completo||'').trim();if(!texto)return `<details class="detalle-seccion texto-fuente"><summary>Texto íntegro del documento</summary><p class="detalle-vacio">El documento individual todavía no se ha capturado. La descripción del índice no sustituye la fuente primaria.</p>${d.enlace_oficial?`<a href="${esc(d.enlace_oficial)}" target="_blank" rel="noopener">Abrir el documento original en la DIAN</a>`:''}</details>`;const fecha=d.enriquecido_en?`<p class="fuente-fecha">Capturado por EUCLIDIAN: ${fechaCorta(d.enriquecido_en)}</p>`:'';return `<details class="detalle-seccion texto-fuente"><summary>Texto capturado del documento DIAN</summary><p class="cobertura-nota">Transcripción de la página oficial capturada. Contrasta con el enlace primario si el formato o el texto son determinantes.</p>${fecha}<pre>${esc(texto)}</pre></details>`;}
function dato(label,value,clase=''){if(value===null||value===undefined||String(value).trim()==='')return '';return `<div class="ficha-dato ${clase}"><span>${esc(label)}</span><strong>${esc(String(value))}</strong></div>`;}
function listaDato(label,arr,max=8){const a=Array.isArray(arr)?arr.filter(Boolean).slice(0,max):[];if(!a.length)return '';return `<div class="ficha-dato ficha-lista"><span>${esc(label)}</span><strong>${a.map(esc).join(' · ')}</strong></div>`;}
function bloqueIdentificacion(d){const fecha=d.fecha_publicacion&&d.fecha_es_real?dato('Fecha del documento',fechaCorta(d.fecha_publicacion),'principal'):'';const filas=[dato('Tipo de documento',d.tipo_documento),dato('Subtipo',d.subtipo),dato('Número',d.numero_resolucion),dato('Número interno',d.numero_interno),dato('Entidad emisora',d.entidad_emisora),dato('Dependencia emisora',d.dependencia_emisora),dato('Área jurídica',d.area_derecho),dato('Diario Oficial',d.diario_oficial),dato('Año del documento',d.anio_publicacion||d.anio),fecha,d.fecha_publicacion_web?dato('Fecha de publicación en la web DIAN',fechaCorta(d.fecha_publicacion_web)):'',dato('Precisión de fecha',d.precision_fecha),dato('Tema DIAN',d.banco_datos),dato('Nivel de detalle',d.nivel_detalle)].filter(Boolean).join('');return filas?`<details class="detalle-seccion ficha-identificacion"><summary>Identificación y fechas</summary><div class="ficha-datos">${filas}</div></details>`:'';}
function bloqueVigencia(d){const retro=d.tiene_efectos_retroactivos===true?'Sí':d.tiene_efectos_retroactivos===false?'No':'No determinado';const filas=[dato('Estado',d.estado_vigencia||'No determinado'),d.fecha_entrada_vigencia&&d.fecha_es_real?dato('Rige desde',fechaCorta(d.fecha_entrada_vigencia)):'',dato('Motivo del estado',d.motivo_cambio_estado),dato('Anotaciones de vigencia',d.anotaciones_vigencia),dato('Efectos retroactivos',retro),listaDato('Años afectados',d.anos_afectados,10),listaDato('Zonas afectadas',d.zonas_afectadas,8),listaDato('Plazos mencionados',d.plazos_mencionados,6)].filter(Boolean).join('');return `<details class="detalle-seccion ficha-vigencia"><summary>Vigencia y efectos</summary><div class="ficha-datos">${filas||'<p class="detalle-vacio">No hay datos adicionales de vigencia registrados.</p>'}</div></details>`;}
function bloqueFuentes(d){const individual=d.enlace_oficial;const indice=d.fuente_raiz||((d.temas||[]).includes('boletin_mensual')?'https://normograma.dian.gov.co/dian/compilacion/novedades_boletines.html':'https://normograma.dian.gov.co/dian/compilacion/tributario.html');const estado=d.estado_fuente_verificacion|| (d.texto_completo?'texto_capturado':'solo_registro');return `<details class="detalle-seccion fuentes"><summary>Fuentes y trazabilidad</summary>${individual?`<div class="fuente-item"><span class="fuente-estado">Documento individual DIAN</span><a href="${esc(individual)}" target="_blank" rel="noopener">Abrir fuente primaria</a></div>`:`<div class="fuente-item"><span class="fuente-estado">Documento individual DIAN</span><span class="fuente-no">No hay enlace individual registrado</span></div>`}<div class="fuente-item"><span class="fuente-estado">Índice oficial DIAN</span><a href="${esc(indice)}" target="_blank" rel="noopener">Ver índice oficial DIAN</a></div><div class="fuente-item"><span class="fuente-estado">Estado de captura</span><span>${esc(estado)}</span></div>${d.fuente_verificada_en?`<div class="fuente-fecha">Fuente verificada: ${fechaCorta(d.fuente_verificada_en)}</div>`:''}${!individual?'<p class="fuente-nota">La ficha se apoya en los datos disponibles del registro oficial DIAN. No se presenta como verificación íntegra del documento si no existe fuente individual accesible.</p>':''}${d.revisado_por_humano&&d.revisado_fiscal_en?`<div class="fuente-fecha">Revisión humana registrada: ${fechaCorta(d.revisado_fiscal_en)}</div>`:d.control_automatico_en?`<div class="fuente-fecha">Control automático registrado: ${fechaCorta(d.control_automatico_en)} · no equivale a aprobación humana</div>`:''}</details>`;}
function bloqueFuentesFormales(d){const partes=[];if((d.fuentes_formales||[]).length)partes.push(listaDato('Fuentes formales',d.fuentes_formales,10));if((d.doctrina_citada||[]).length)partes.push(listaDato('Doctrina citada',d.doctrina_citada,8));if((d.jurisprudencia_citada||[]).length)partes.push(listaDato('Jurisprudencia citada',d.jurisprudencia_citada,8));if((d.descriptores||[]).length)partes.push(listaDato('Descriptores',d.descriptores,10));return partes.length?`<details class="detalle-seccion"><summary>Fuentes jurídicas y descriptores</summary><div class="ficha-datos">${partes.join('')}</div></details>`:'';}
function bloqueRelaciones(d){const despues=d.modificado_por||[];const antes=d.modifica_a||[];if(!despues.length&&!antes.length)return '';let html='';if(despues.length){const items=despues.slice(0,6).map(r=>`<li>${esc(r.accion||'modificada')} por <a href="${esc(r.enlace||'#')}" target="_blank" rel="noopener">${esc(r.numero||'')}</a> ${r.fecha?`<span class="rel-fecha">(${fechaCorta(r.fecha)})</span>`:''}</li>`).join('');html+=`<div class="rel despues"><b>Normas posteriores relacionadas</b><ul>${items}${despues.length>6?`<li class="rel-mas">y ${despues.length-6} más</li>`:''}</ul></div>`;}if(antes.length){const items=antes.slice(0,6).map(r=>`<li>${esc(r.accion||'modifica')} a <a href="${esc(r.enlace||'#')}" target="_blank" rel="noopener">${esc(r.numero||'')}</a></li>`).join('');html+=`<div class="rel antes"><b>Normas que esta ficha modifica</b><ul>${items}${antes.length>6?`<li class="rel-mas">y ${antes.length-6} más</li>`:''}</ul></div>`;}return html;}
function bloquePlazo(d){const p=(d.plazos_mencionados||[])[0];if(!p)return '';const f=fechaDePlazo(p);let marca='';if(f){const n=diasHasta(f);marca=n>=0?`<span class="restan ${n>30?'lejos':''}">${n===0?'hoy':n===1?'mañana':'faltan '+n+' días'}</span>`:`<span class="restan pasado">ya pasó</span>`;}return `<div class="plazo"><div class="plazo-cab"><span>Plazo</span>${marca}</div><p>${esc(p)}</p></div>`;}
function bloqueClasificacion(d){const temas=(d.temas||[]).filter(t=>!t.startsWith('dian:')&&t!=='boletin_mensual');const vigenciaIndeterminada=!d.estado_vigencia||d.estado_vigencia==='desconocido';const fuerza=[`<span class="${vigenciaIndeterminada?'orienta':d.estado_vigencia!=='vigente'?'alerta':d.clasificacion_obligatoriedad==='obligatorio_dian_y_contribuyentes'?'obliga':'orienta'}">${leyenda(d)}</span>`,d.tiene_efectos_retroactivos===true?'<span class="alerta">afecta años pasados</span>':'',d.nivel_alerta?`<span>${esc(d.nivel_alerta)}</span>`:'',d.prioridad?`<span>${esc(d.prioridad)}</span>`:''].filter(Boolean).join('');const materias=[d.materia?`<span class="materia">${esc(d.materia)}</span>`:'',...temas.slice(0,8).map(t=>`<span>${nombreTema(t)}</span>`)].filter(Boolean).join('');return `<div class="clasificacion"><div class="grupo-marcas"><span class="clas-rotulo">Qué fuerza tiene</span><div class="marcas">${fuerza||'<span>Sin clasificación registrada</span>'}</div></div><div class="grupo-marcas"><span class="clas-rotulo">De qué trata</span><div class="marcas">${materias||'<span>Sin materia/tema registrado</span>'}</div></div></div>`;}
function ficha(d){const s=señal(d);const marcaNueva=d.es_nuevo?'<span class="nuevo">Nuevo</span>':'';const marcaDetalle=d.nivel_detalle==='solo_listado'?'<span class="detalle-parcial">Sin abrir</span>':d.nivel_detalle==='leido'?'<span class="detalle-parcial">Sin ficha</span>':'';const lateral=[bloquePlazo(d),bloqueRelaciones(d)].filter(Boolean).join('');const descriptores=(d.descriptores||[]).length?`<ul>${d.descriptores.slice(0,10).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';return `<article data-id="${d.id}" class="t-${s.tono}${d.resumen_humano?' escrito':''}${d.es_nuevo?' nuevo-doc':''}><div class="cintas">${marcaNueva}<span class="cinta">${s.rotulo}</span>${marcaDetalle}</div><div class="fila-id">${glifo(d)}<a class="codigo" href="${esc(d.enlace_oficial||'#')}" target="_blank" rel="noopener">${esc(d.numero_resolucion)}</a>${d.numero_interno?`<span class="interno">int ${esc(d.numero_interno)}</span>`:''}${d.fecha_publicacion?`<span class="fecha-principal">Publicado DIAN · ${fechaCorta(d.fecha_publicacion)}</span>`:fechaFicha(d)}</div><h2>${esc(d.titulo||d.numero_resolucion||'Documento DIAN')}</h2><div class="cuerpo"><div class="principal">${bloqueDiagnostico(d)}${bloqueCobertura(d)}${bloqueContenido(d)}${bloqueRespuesta(d)}${bloqueIdentificacion(d)}${bloqueVigencia(d)}${bloqueFuentesFormales(d)}${bloqueFuentes(d)}${d.descripcion_limpia||d.contenido?`<details class="oficial"><summary><span class="abrir">Ver texto de la DIAN</span></summary><p>${esc(d.descripcion_limpia||d.contenido)}</p>${descriptores}</details>`:''}${bloqueClasificacion(d)}</div>${lateral?`<aside class="lateral">${lateral}</aside>`:''}</div></article>`;}

// Keep the source document distinct from the short description in the index.
const fichaBaseEUCLIDIAN = ficha;
ficha = function(d){
  let html=fichaBaseEUCLIDIAN(d)
    .replace('Ver texto de la DIAN','Descripción del índice DIAN')
    .replace('Publicado DIAN ·','Fecha del documento ·');
  if(!d.fecha_es_real){
    const anio=esc(d.anio_publicacion||d.anio||'no determinado');
    html=html.replace(/<span class="fecha-principal">Fecha del documento · [^<]*<\/span>/,`<span class="fecha-principal">Fecha exacta no confirmada · ${anio}</span>`);
  }
  return html.replace('</article>',`${bloqueTextoFuente(d)}${window.euclidianPuedeRevisar?bloqueAcciones(d):''}</article>`);
};

function bloqueAcciones(d){
  const id=String(d.id??'');
  if(!id)return '';
  const attr=esc(id);
  const texto=esc(d.resumen_humano||d.resumen_borrador||'');
  return `<section class="revision-editor" aria-label="Revisión humana"><label for="r-${attr}">Síntesis clara para el contador</label><textarea id="r-${attr}" maxlength="4000" rows="5" oninput="contar(this.id.slice(2))">${texto}</textarea><div class="revision-ayuda">Separa esta síntesis del texto literal de la DIAN. La revisión humana puede corregirla antes de publicarla.</div><button type="button" data-review-save="${attr}">Guardar síntesis</button><div class="revision-acciones"><button type="button" data-review-decision="aprobar" data-review-id="${attr}">Aprobar y publicar ficha</button><button type="button" class="secundario" data-review-decision="descartar" data-review-id="${attr}">Descartar ficha</button></div></section>`;
}
if(!window.__euclidianReviewActions){window.__euclidianReviewActions=true;document.addEventListener('click',e=>{const save=e.target.closest('[data-review-save]');if(save){guardarResumen(save.dataset.reviewSave);return;}const decision=e.target.closest('[data-review-decision]');if(decision)decidir(decision.dataset.reviewId,decision.dataset.reviewDecision);});}
